import Fuse from "fuse.js";

/**
 * Supported Category Definitions with Indian-friendly visual styles and icons
 */
export const CATEGORIES = [
  { id: "Food", label: "Food & Groceries", color: "from-amber-500 to-orange-500", badgeBg: "bg-amber-500/10 text-amber-400 border-amber-500/20", icon: "🍔" },
  { id: "Transport", label: "Travel & Commute", color: "from-blue-500 to-cyan-500", badgeBg: "bg-blue-500/10 text-blue-400 border-blue-500/20", icon: "🚗" },
  { id: "Shopping", label: "Shopping & Retail", color: "from-purple-500 to-pink-500", badgeBg: "bg-purple-500/10 text-purple-400 border-purple-500/20", icon: "🛍️" },
  { id: "Entertainment", label: "Entertainment & OTT", color: "from-rose-500 to-red-500", badgeBg: "bg-rose-500/10 text-rose-400 border-rose-500/20", icon: "🎬" },
  { id: "Bills", label: "Bills & Utilities", color: "from-yellow-500 to-amber-600", badgeBg: "bg-yellow-500/10 text-yellow-400 border-yellow-500/20", icon: "⚡" },
  { id: "Health", label: "Health & Fitness", color: "from-emerald-500 to-teal-500", badgeBg: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20", icon: "💊" },
  { id: "Education", label: "Education & Coaching", color: "from-indigo-500 to-blue-600", badgeBg: "bg-indigo-500/10 text-indigo-400 border-indigo-500/20", icon: "📚" },
  { id: "Salary", label: "Salary & Inflows", color: "from-green-500 to-emerald-600", badgeBg: "bg-green-500/10 text-green-400 border-green-500/20", icon: "💰" },
  { id: "Freelance", label: "Freelance & Business", color: "from-teal-500 to-cyan-600", badgeBg: "bg-teal-500/10 text-teal-400 border-teal-500/20", icon: "💼" },
  { id: "Investment", label: "Investments & Gold", color: "from-violet-500 to-purple-600", badgeBg: "bg-violet-500/10 text-violet-400 border-violet-500/20", icon: "📈" },
  { id: "Gift", label: "Gifts, Shagun & Daan", color: "from-pink-500 to-rose-400", badgeBg: "bg-pink-500/10 text-pink-400 border-pink-500/20", icon: "🎁" },
  { id: "Other", label: "Other / General", color: "from-slate-500 to-gray-500", badgeBg: "bg-slate-500/10 text-slate-400 border-slate-500/20", icon: "🏷️" },
];

/**
 * Massive Indian-Centric Training Knowledge Base for Fuzzy Keyword Matching (500+ items)
 */
const INDIAN_TRAINING_DATA = [
  // 1. Food Delivery, Quick Commerce & Cloud Kitchens
  { keyword: "swiggy", category: "Food", type: "expense" },
  { keyword: "swiggy instamart", category: "Food", type: "expense" },
  { keyword: "swiggy dineout", category: "Food", type: "expense" },
  { keyword: "swiggy gourmet", category: "Food", type: "expense" },
  { keyword: "zomato", category: "Food", type: "expense" },
  { keyword: "zomato gold", category: "Food", type: "expense" },
  { keyword: "zomato feeding india", category: "Food", type: "expense" },
  { keyword: "blinkit", category: "Food", type: "expense" },
  { keyword: "zepto", category: "Food", type: "expense" },
  { keyword: "zepto cafe", category: "Food", type: "expense" },
  { keyword: "instamart", category: "Food", type: "expense" },
  { keyword: "bigbasket", category: "Food", type: "expense" },
  { keyword: "bb daily", category: "Food", type: "expense" },
  { keyword: "bb now", category: "Food", type: "expense" },
  { keyword: "dunzo", category: "Food", type: "expense" },
  { keyword: "eatclub", category: "Food", type: "expense" },
  { keyword: "magicpin", category: "Food", type: "expense" },
  { keyword: "ovenstory", category: "Food", type: "expense" },
  { keyword: "behrouz", category: "Food", type: "expense" },
  { keyword: "behrouz biryani", category: "Food", type: "expense" },
  { keyword: "faasos", category: "Food", type: "expense" },
  { keyword: "box8", category: "Food", type: "expense" },
  { keyword: "freshmenu", category: "Food", type: "expense" },
  { keyword: "mojo pizza", category: "Food", type: "expense" },
  { keyword: "firangi bake", category: "Food", type: "expense" },
  { keyword: "sweet truth", category: "Food", type: "expense" },
  { keyword: "lunchbox", category: "Food", type: "expense" },
  { keyword: "the good bowl", category: "Food", type: "expense" },
  { keyword: "bakingo", category: "Food", type: "expense" },
  { keyword: "fnp cakes", category: "Food", type: "expense" },
  { keyword: "winni", category: "Food", type: "expense" },

  // Restaurants, Chains, Cafes & Fast Food
  { keyword: "haldirams", category: "Food", type: "expense" },
  { keyword: "bikanervala", category: "Food", type: "expense" },
  { keyword: "saravana bhavan", category: "Food", type: "expense" },
  { keyword: "sagar ratna", category: "Food", type: "expense" },
  { keyword: "murugan idli", category: "Food", type: "expense" },
  { keyword: "mcdonalds", category: "Food", type: "expense" },
  { keyword: "dominos", category: "Food", type: "expense" },
  { keyword: "pizza hut", category: "Food", type: "expense" },
  { keyword: "kfc", category: "Food", type: "expense" },
  { keyword: "burger king", category: "Food", type: "expense" },
  { keyword: "subway", category: "Food", type: "expense" },
  { keyword: "starbucks", category: "Food", type: "expense" },
  { keyword: "chaayos", category: "Food", type: "expense" },
  { keyword: "chai point", category: "Food", type: "expense" },
  { keyword: "cafe coffee day", category: "Food", type: "expense" },
  { keyword: "ccd", category: "Food", type: "expense" },
  { keyword: "theobroma", category: "Food", type: "expense" },
  { keyword: "wow momo", category: "Food", type: "expense" },
  { keyword: "wow china", category: "Food", type: "expense" },
  { keyword: "biryani by kilo", category: "Food", type: "expense" },
  { keyword: "paradise biryani", category: "Food", type: "expense" },
  { keyword: "barbeque nation", category: "Food", type: "expense" },
  { keyword: "absolute barbecues", category: "Food", type: "expense" },
  { keyword: "mainland china", category: "Food", type: "expense" },
  { keyword: "punjab grill", category: "Food", type: "expense" },
  { keyword: "social", category: "Food", type: "expense" },
  { keyword: "gillys", category: "Food", type: "expense" },
  { keyword: "toit", category: "Food", type: "expense" },
  { keyword: "smoke house deli", category: "Food", type: "expense" },
  { keyword: "taco bell", category: "Food", type: "expense" },
  { keyword: "pind balluchi", category: "Food", type: "expense" },
  { keyword: "naturals ice cream", category: "Food", type: "expense" },
  { keyword: "giani", category: "Food", type: "expense" },
  { keyword: "havmor", category: "Food", type: "expense" },
  { keyword: "kwality walls", category: "Food", type: "expense" },
  { keyword: "amul ice cream", category: "Food", type: "expense" },
  { keyword: "baskin robbins", category: "Food", type: "expense" },
  { keyword: "arun ice cream", category: "Food", type: "expense" },
  { keyword: "polar bear", category: "Food", type: "expense" },
  { keyword: "corner house", category: "Food", type: "expense" },
  { keyword: "keventers", category: "Food", type: "expense" },

  // Indian Street Food, Snacks, Sweets & Beverages
  { keyword: "chai", category: "Food", type: "expense" },
  { keyword: "tea", category: "Food", type: "expense" },
  { keyword: "coffee", category: "Food", type: "expense" },
  { keyword: "filter coffee", category: "Food", type: "expense" },
  { keyword: "tapri", category: "Food", type: "expense" },
  { keyword: "kulhad chai", category: "Food", type: "expense" },
  { keyword: "cutting chai", category: "Food", type: "expense" },
  { keyword: "samosa", category: "Food", type: "expense" },
  { keyword: "kachori", category: "Food", type: "expense" },
  { keyword: "jalebi", category: "Food", type: "expense" },
  { keyword: "dhokla", category: "Food", type: "expense" },
  { keyword: "khaman", category: "Food", type: "expense" },
  { keyword: "fafda", category: "Food", type: "expense" },
  { keyword: "poha", category: "Food", type: "expense" },
  { keyword: "upma", category: "Food", type: "expense" },
  { keyword: "sheera", category: "Food", type: "expense" },
  { keyword: "dosa", category: "Food", type: "expense" },
  { keyword: "masala dosa", category: "Food", type: "expense" },
  { keyword: "idli", category: "Food", type: "expense" },
  { keyword: "vada", category: "Food", type: "expense" },
  { keyword: "medu vada", category: "Food", type: "expense" },
  { keyword: "vada pav", category: "Food", type: "expense" },
  { keyword: "misal pav", category: "Food", type: "expense" },
  { keyword: "pav bhaji", category: "Food", type: "expense" },
  { keyword: "pani puri", category: "Food", type: "expense" },
  { keyword: "golgappa", category: "Food", type: "expense" },
  { keyword: "puchka", category: "Food", type: "expense" },
  { keyword: "chaat", category: "Food", type: "expense" },
  { keyword: "bhel puri", category: "Food", type: "expense" },
  { keyword: "sev puri", category: "Food", type: "expense" },
  { keyword: "dahi puri", category: "Food", type: "expense" },
  { keyword: "aloo tikki", category: "Food", type: "expense" },
  { keyword: "chole bhature", category: "Food", type: "expense" },
  { keyword: "chole kulche", category: "Food", type: "expense" },
  { keyword: "paratha", category: "Food", type: "expense" },
  { keyword: "aloo paratha", category: "Food", type: "expense" },
  { keyword: "paneer paratha", category: "Food", type: "expense" },
  { keyword: "thali", category: "Food", type: "expense" },
  { keyword: "rajma chawal", category: "Food", type: "expense" },
  { keyword: "kadhi chawal", category: "Food", type: "expense" },
  { keyword: "dal makhani", category: "Food", type: "expense" },
  { keyword: "butter chicken", category: "Food", type: "expense" },
  { keyword: "paneer", category: "Food", type: "expense" },
  { keyword: "biryani", category: "Food", type: "expense" },
  { keyword: "kathi roll", category: "Food", type: "expense" },
  { keyword: "shawarma", category: "Food", type: "expense" },
  { keyword: "momos", category: "Food", type: "expense" },
  { keyword: "spring roll", category: "Food", type: "expense" },
  { keyword: "chowmein", category: "Food", type: "expense" },
  { keyword: "fried rice", category: "Food", type: "expense" },
  { keyword: "manchurian", category: "Food", type: "expense" },
  { keyword: "noodles", category: "Food", type: "expense" },
  { keyword: "maggi", category: "Food", type: "expense" },
  { keyword: "canteen", category: "Food", type: "expense" },
  { keyword: "mess", category: "Food", type: "expense" },
  { keyword: "tiffin", category: "Food", type: "expense" },
  { keyword: "dabba", category: "Food", type: "expense" },
  { keyword: "dhaba", category: "Food", type: "expense" },
  { keyword: "sweet shop", category: "Food", type: "expense" },
  { keyword: "mithai", category: "Food", type: "expense" },
  { keyword: "rasgulla", category: "Food", type: "expense" },
  { keyword: "gulab jamun", category: "Food", type: "expense" },
  { keyword: "kaju katli", category: "Food", type: "expense" },
  { keyword: "laddu", category: "Food", type: "expense" },
  { keyword: "barfi", category: "Food", type: "expense" },
  { keyword: "lassi", category: "Food", type: "expense" },
  { keyword: "chaas", category: "Food", type: "expense" },
  { keyword: "buttermilk", category: "Food", type: "expense" },
  { keyword: "badam milk", category: "Food", type: "expense" },
  { keyword: "falooda", category: "Food", type: "expense" },
  { keyword: "sugarcane juice", category: "Food", type: "expense" },
  { keyword: "nariyal pani", category: "Food", type: "expense" },
  { keyword: "tender coconut", category: "Food", type: "expense" },
  { keyword: "juice shop", category: "Food", type: "expense" },
  { keyword: "smoothie", category: "Food", type: "expense" },

  // Kirana, Dairy, Supermarket & Meat
  { keyword: "kirana", category: "Food", type: "expense" },
  { keyword: "ration", category: "Food", type: "expense" },
  { keyword: "sabzi", category: "Food", type: "expense" },
  { keyword: "vegetables", category: "Food", type: "expense" },
  { keyword: "fruits", category: "Food", type: "expense" },
  { keyword: "mandi", category: "Food", type: "expense" },
  { keyword: "dmart", category: "Food", type: "expense" },
  { keyword: "d-mart", category: "Food", type: "expense" },
  { keyword: "reliance fresh", category: "Food", type: "expense" },
  { keyword: "reliance smart", category: "Food", type: "expense" },
  { keyword: "smart bazaar", category: "Food", type: "expense" },
  { keyword: "nature's basket", category: "Food", type: "expense" },
  { keyword: "spencers", category: "Food", type: "expense" },
  { keyword: "more retail", category: "Food", type: "expense" },
  { keyword: "star bazaar", category: "Food", type: "expense" },
  { keyword: "lulu hypermarket", category: "Food", type: "expense" },
  { keyword: "milk", category: "Food", type: "expense" },
  { keyword: "doodh", category: "Food", type: "expense" },
  { keyword: "amul", category: "Food", type: "expense" },
  { keyword: "mother dairy", category: "Food", type: "expense" },
  { keyword: "nandini", category: "Food", type: "expense" },
  { keyword: "country delight", category: "Food", type: "expense" },
  { keyword: "akshayakalpa", category: "Food", type: "expense" },
  { keyword: "milkbasket", category: "Food", type: "expense" },
  { keyword: "licious", category: "Food", type: "expense" },
  { keyword: "fresh2home", category: "Food", type: "expense" },
  { keyword: "meatigo", category: "Food", type: "expense" },
  { keyword: "egg store", category: "Food", type: "expense" },
  { keyword: "chicken shop", category: "Food", type: "expense" },
  { keyword: "mutton shop", category: "Food", type: "expense" },
  { keyword: "fish market", category: "Food", type: "expense" },
  { keyword: "atta", category: "Food", type: "expense" },
  { keyword: "rice", category: "Food", type: "expense" },
  { keyword: "dal", category: "Food", type: "expense" },
  { keyword: "oil", category: "Food", type: "expense" },
  { keyword: "ghee", category: "Food", type: "expense" },
  { keyword: "spices", category: "Food", type: "expense" },
  { keyword: "groceries", category: "Food", type: "expense" },
  { keyword: "grocery", category: "Food", type: "expense" },
  { keyword: "supermarket", category: "Food", type: "expense" },
  { keyword: "bakery", category: "Food", type: "expense" },
  { keyword: "restaurant", category: "Food", type: "expense" },
  { keyword: "lunch", category: "Food", type: "expense" },
  { keyword: "dinner", category: "Food", type: "expense" },
  { keyword: "breakfast", category: "Food", type: "expense" },
  { keyword: "snack", category: "Food", type: "expense" },

  // 2. Transport, Cabs, Metro, Railways, Fuel & Flights
  { keyword: "ola", category: "Transport", type: "expense" },
  { keyword: "ola cabs", category: "Transport", type: "expense" },
  { keyword: "ola auto", category: "Transport", type: "expense" },
  { keyword: "ola bike", category: "Transport", type: "expense" },
  { keyword: "uber", category: "Transport", type: "expense" },
  { keyword: "uber auto", category: "Transport", type: "expense" },
  { keyword: "uber moto", category: "Transport", type: "expense" },
  { keyword: "rapido", category: "Transport", type: "expense" },
  { keyword: "rapido bike", category: "Transport", type: "expense" },
  { keyword: "rapido auto", category: "Transport", type: "expense" },
  { keyword: "namma yatri", category: "Transport", type: "expense" },
  { keyword: "indrive", category: "Transport", type: "expense" },
  { keyword: "auto", category: "Transport", type: "expense" },
  { keyword: "auto rickshaw", category: "Transport", type: "expense" },
  { keyword: "rickshaw", category: "Transport", type: "expense" },
  { keyword: "e-rickshaw", category: "Transport", type: "expense" },
  { keyword: "toto", category: "Transport", type: "expense" },
  { keyword: "cab", category: "Transport", type: "expense" },
  { keyword: "taxi", category: "Transport", type: "expense" },
  { keyword: "kaali peeli", category: "Transport", type: "expense" },
  { keyword: "zoomcar", category: "Transport", type: "expense" },
  { keyword: "revv", category: "Transport", type: "expense" },
  { keyword: "drivezy", category: "Transport", type: "expense" },

  // Train, Metro, Bus & Public Transit
  { keyword: "irctc", category: "Transport", type: "expense" },
  { keyword: "train ticket", category: "Transport", type: "expense" },
  { keyword: "tatkal", category: "Transport", type: "expense" },
  { keyword: "railway ticket", category: "Transport", type: "expense" },
  { keyword: "indian railways", category: "Transport", type: "expense" },
  { keyword: "uts", category: "Transport", type: "expense" },
  { keyword: "uts ticket", category: "Transport", type: "expense" },
  { keyword: "local train", category: "Transport", type: "expense" },
  { keyword: "mumbai local", category: "Transport", type: "expense" },
  { keyword: "metro", category: "Transport", type: "expense" },
  { keyword: "dmrc", category: "Transport", type: "expense" },
  { keyword: "delhi metro", category: "Transport", type: "expense" },
  { keyword: "bmrc", category: "Transport", type: "expense" },
  { keyword: "namma metro", category: "Transport", type: "expense" },
  { keyword: "mumbai metro", category: "Transport", type: "expense" },
  { keyword: "maha metro", category: "Transport", type: "expense" },
  { keyword: "hyderabad metro", category: "Transport", type: "expense" },
  { keyword: "chennai metro", category: "Transport", type: "expense" },
  { keyword: "kolkata metro", category: "Transport", type: "expense" },
  { keyword: "chalo app", category: "Transport", type: "expense" },
  { keyword: "chalo card", category: "Transport", type: "expense" },
  { keyword: "redbus", category: "Transport", type: "expense" },
  { keyword: "abhibus", category: "Transport", type: "expense" },
  { keyword: "zingbus", category: "Transport", type: "expense" },
  { keyword: "ksrtc", category: "Transport", type: "expense" },
  { keyword: "msrtc", category: "Transport", type: "expense" },
  { keyword: "upsrtc", category: "Transport", type: "expense" },
  { keyword: "gsrtc", category: "Transport", type: "expense" },
  { keyword: "hrctc", category: "Transport", type: "expense" },
  { keyword: "bmtc", category: "Transport", type: "expense" },
  { keyword: "best bus", category: "Transport", type: "expense" },
  { keyword: "dtc bus", category: "Transport", type: "expense" },
  { keyword: "bus fare", category: "Transport", type: "expense" },
  { keyword: "ferry", category: "Transport", type: "expense" },

  // Fuel, Toll, Parking & Vehicle Services
  { keyword: "petrol", category: "Transport", type: "expense" },
  { keyword: "diesel", category: "Transport", type: "expense" },
  { keyword: "cng", category: "Transport", type: "expense" },
  { keyword: "fuel", category: "Transport", type: "expense" },
  { keyword: "indian oil", category: "Transport", type: "expense" },
  { keyword: "ioc", category: "Transport", type: "expense" },
  { keyword: "iocl", category: "Transport", type: "expense" },
  { keyword: "hp petrol", category: "Transport", type: "expense" },
  { keyword: "hpcl", category: "Transport", type: "expense" },
  { keyword: "bharat petroleum", category: "Transport", type: "expense" },
  { keyword: "bpcl", category: "Transport", type: "expense" },
  { keyword: "shell petrol", category: "Transport", type: "expense" },
  { keyword: "nayara", category: "Transport", type: "expense" },
  { keyword: "jio-bp", category: "Transport", type: "expense" },
  { keyword: "xp95", category: "Transport", type: "expense" },
  { keyword: "ev charging", category: "Transport", type: "expense" },
  { keyword: "tata power ev", category: "Transport", type: "expense" },
  { keyword: "ather grid", category: "Transport", type: "expense" },
  { keyword: "fastag", category: "Transport", type: "expense" },
  { keyword: "fastag recharge", category: "Transport", type: "expense" },
  { keyword: "nhai toll", category: "Transport", type: "expense" },
  { keyword: "toll plaza", category: "Transport", type: "expense" },
  { keyword: "toll tax", category: "Transport", type: "expense" },
  { keyword: "parking", category: "Transport", type: "expense" },
  { keyword: "car service", category: "Transport", type: "expense" },
  { keyword: "bike service", category: "Transport", type: "expense" },
  { keyword: "car repair", category: "Transport", type: "expense" },
  { keyword: "bike repair", category: "Transport", type: "expense" },
  { keyword: "puncture", category: "Transport", type: "expense" },
  { keyword: "wheel alignment", category: "Transport", type: "expense" },
  { keyword: "car wash", category: "Transport", type: "expense" },
  { keyword: "bike wash", category: "Transport", type: "expense" },
  { keyword: "puc", category: "Transport", type: "expense" },
  { keyword: "challan", category: "Transport", type: "expense" },
  { keyword: "traffic challan", category: "Transport", type: "expense" },
  { keyword: "parivahan", category: "Transport", type: "expense" },
  { keyword: "rto fee", category: "Transport", type: "expense" },
  { keyword: "car insurance", category: "Transport", type: "expense" },
  { keyword: "bike insurance", category: "Transport", type: "expense" },
  { keyword: "acko insurance", category: "Transport", type: "expense" },
  { keyword: "digit insurance", category: "Transport", type: "expense" },

  // Flights & Travel Portals
  { keyword: "indigo", category: "Transport", type: "expense" },
  { keyword: "air india", category: "Transport", type: "expense" },
  { keyword: "spicejet", category: "Transport", type: "expense" },
  { keyword: "akasa air", category: "Transport", type: "expense" },
  { keyword: "vistara", category: "Transport", type: "expense" },
  { keyword: "air india express", category: "Transport", type: "expense" },
  { keyword: "flight ticket", category: "Transport", type: "expense" },
  { keyword: "airline", category: "Transport", type: "expense" },
  { keyword: "makemytrip", category: "Transport", type: "expense" },
  { keyword: "mmt", category: "Transport", type: "expense" },
  { keyword: "easemytrip", category: "Transport", type: "expense" },
  { keyword: "yatra", category: "Transport", type: "expense" },
  { keyword: "cleartrip", category: "Transport", type: "expense" },
  { keyword: "ixigo", category: "Transport", type: "expense" },
  { keyword: "goibibo", category: "Transport", type: "expense" },
  { keyword: "oyo", category: "Transport", type: "expense" },
  { keyword: "treebo", category: "Transport", type: "expense" },
  { keyword: "fabhotels", category: "Transport", type: "expense" },
  { keyword: "taj hotel", category: "Transport", type: "expense" },
  { keyword: "itc hotel", category: "Transport", type: "expense" },
  { keyword: "hotel stay", category: "Transport", type: "expense" },
  { keyword: "resort", category: "Transport", type: "expense" },

  // 3. Shopping, E-Commerce, Fashion, Retail & Jewelry
  { keyword: "flipkart", category: "Shopping", type: "expense" },
  { keyword: "amazon", category: "Shopping", type: "expense" },
  { keyword: "amazon in", category: "Shopping", type: "expense" },
  { keyword: "amazon pay", category: "Shopping", type: "expense" },
  { keyword: "meesho", category: "Shopping", type: "expense" },
  { keyword: "myntra", category: "Shopping", type: "expense" },
  { keyword: "ajio", category: "Shopping", type: "expense" },
  { keyword: "tata cliq", category: "Shopping", type: "expense" },
  { keyword: "nykaa", category: "Shopping", type: "expense" },
  { keyword: "purplle", category: "Shopping", type: "expense" },
  { keyword: "shopsy", category: "Shopping", type: "expense" },
  { keyword: "snapdeal", category: "Shopping", type: "expense" },
  { keyword: "firstcry", category: "Shopping", type: "expense" },
  { keyword: "hopscotch", category: "Shopping", type: "expense" },
  { keyword: "urbanic", category: "Shopping", type: "expense" },
  { keyword: "bewakoof", category: "Shopping", type: "expense" },
  { keyword: "snitch", category: "Shopping", type: "expense" },
  { keyword: "the souled store", category: "Shopping", type: "expense" },
  { keyword: "blissclub", category: "Shopping", type: "expense" },
  { keyword: "clovia", category: "Shopping", type: "expense" },
  { keyword: "zivame", category: "Shopping", type: "expense" },
  { keyword: "zudio", category: "Shopping", type: "expense" },
  { keyword: "trends", category: "Shopping", type: "expense" },
  { keyword: "reliance trends", category: "Shopping", type: "expense" },
  { keyword: "max fashion", category: "Shopping", type: "expense" },
  { keyword: "pantaloons", category: "Shopping", type: "expense" },
  { keyword: "westside", category: "Shopping", type: "expense" },
  { keyword: "lifestyle", category: "Shopping", type: "expense" },
  { keyword: "shoppers stop", category: "Shopping", type: "expense" },
  { keyword: "zara", category: "Shopping", type: "expense" },
  { keyword: "h&m", category: "Shopping", type: "expense" },
  { keyword: "uniqlo", category: "Shopping", type: "expense" },
  { keyword: "marks and spencer", category: "Shopping", type: "expense" },
  { keyword: "fabindia", category: "Shopping", type: "expense" },
  { keyword: "manyavar", category: "Shopping", type: "expense" },
  { keyword: "mohey", category: "Shopping", type: "expense" },
  { keyword: "w for woman", category: "Shopping", type: "expense" },
  { keyword: "biba", category: "Shopping", type: "expense" },
  { keyword: "soch", category: "Shopping", type: "expense" },
  { keyword: "bata", category: "Shopping", type: "expense" },
  { keyword: "woodland", category: "Shopping", type: "expense" },
  { keyword: "red chief", category: "Shopping", type: "expense" },
  { keyword: "metro shoes", category: "Shopping", type: "expense" },
  { keyword: "mochi", category: "Shopping", type: "expense" },
  { keyword: "decathlon", category: "Shopping", type: "expense" },
  { keyword: "puma", category: "Shopping", type: "expense" },
  { keyword: "nike", category: "Shopping", type: "expense" },
  { keyword: "adidas", category: "Shopping", type: "expense" },
  { keyword: "skechers", category: "Shopping", type: "expense" },
  { keyword: "asics", category: "Shopping", type: "expense" },
  { keyword: "wildcraft", category: "Shopping", type: "expense" },
  { keyword: "safari luggage", category: "Shopping", type: "expense" },
  { keyword: "vip luggage", category: "Shopping", type: "expense" },
  { keyword: "american tourister", category: "Shopping", type: "expense" },
  { keyword: "skybags", category: "Shopping", type: "expense" },
  { keyword: "lenskart", category: "Shopping", type: "expense" },
  { keyword: "titan eyeplus", category: "Shopping", type: "expense" },
  { keyword: "titan", category: "Shopping", type: "expense" },
  { keyword: "fastrack", category: "Shopping", type: "expense" },
  { keyword: "casio", category: "Shopping", type: "expense" },
  { keyword: "tanishq", category: "Shopping", type: "expense" },
  { keyword: "kalyan jewellers", category: "Shopping", type: "expense" },
  { keyword: "malabar gold", category: "Shopping", type: "expense" },
  { keyword: "joyalukkas", category: "Shopping", type: "expense" },
  { keyword: "grt jewellers", category: "Shopping", type: "expense" },
  { keyword: "caratlane", category: "Shopping", type: "expense" },
  { keyword: "bluestone", category: "Shopping", type: "expense" },
  { keyword: "giva", category: "Shopping", type: "expense" },
  { keyword: "croma", category: "Shopping", type: "expense" },
  { keyword: "reliance digital", category: "Shopping", type: "expense" },
  { keyword: "vijay sales", category: "Shopping", type: "expense" },
  { keyword: "poorvika", category: "Shopping", type: "expense" },
  { keyword: "sangeetha", category: "Shopping", type: "expense" },
  { keyword: "apple store", category: "Shopping", type: "expense" },
  { keyword: "samsung store", category: "Shopping", type: "expense" },
  { keyword: "oneplus store", category: "Shopping", type: "expense" },
  { keyword: "mi store", category: "Shopping", type: "expense" },
  { keyword: "boat", category: "Shopping", type: "expense" },
  { keyword: "noise", category: "Shopping", type: "expense" },
  { keyword: "fire-boltt", category: "Shopping", type: "expense" },
  { keyword: "ikea", category: "Shopping", type: "expense" },
  { keyword: "home centre", category: "Shopping", type: "expense" },
  { keyword: "wakefit", category: "Shopping", type: "expense" },
  { keyword: "sleepwell", category: "Shopping", type: "expense" },
  { keyword: "pepperfry", category: "Shopping", type: "expense" },
  { keyword: "urban ladder", category: "Shopping", type: "expense" },
  { keyword: "local bazaar", category: "Shopping", type: "expense" },
  { keyword: "tailor", category: "Shopping", type: "expense" },
  { keyword: "boutique", category: "Shopping", type: "expense" },
  { keyword: "dry clean", category: "Shopping", type: "expense" },
  { keyword: "ironing", category: "Shopping", type: "expense" },
  { keyword: "puja items", category: "Shopping", type: "expense" },
  { keyword: "diwali shopping", category: "Shopping", type: "expense" },
  { keyword: "rakhi shopping", category: "Shopping", type: "expense" },
  { keyword: "clothing", category: "Shopping", type: "expense" },
  { keyword: "clothes", category: "Shopping", type: "expense" },
  { keyword: "shoes", category: "Shopping", type: "expense" },

  // 4. Bills, Utilities, Rent, Domestic Services & Discoms
  { keyword: "jio", category: "Bills", type: "expense" },
  { keyword: "jio recharge", category: "Bills", type: "expense" },
  { keyword: "jio fiber", category: "Bills", type: "expense" },
  { keyword: "airtel", category: "Bills", type: "expense" },
  { keyword: "airtel recharge", category: "Bills", type: "expense" },
  { keyword: "airtel fiber", category: "Bills", type: "expense" },
  { keyword: "airtel xstream", category: "Bills", type: "expense" },
  { keyword: "vi", category: "Bills", type: "expense" },
  { keyword: "vodafone", category: "Bills", type: "expense" },
  { keyword: "bsnl", category: "Bills", type: "expense" },
  { keyword: "act fibernet", category: "Bills", type: "expense" },
  { keyword: "hathway", category: "Bills", type: "expense" },
  { keyword: "tata play fiber", category: "Bills", type: "expense" },
  { keyword: "excitel", category: "Bills", type: "expense" },
  { keyword: "wifi bill", category: "Bills", type: "expense" },
  { keyword: "broadband", category: "Bills", type: "expense" },
  { keyword: "postpaid bill", category: "Bills", type: "expense" },
  { keyword: "mobile recharge", category: "Bills", type: "expense" },
  { keyword: "electricity bill", category: "Bills", type: "expense" },
  { keyword: "bijli bill", category: "Bills", type: "expense" },
  { keyword: "light bill", category: "Bills", type: "expense" },
  { keyword: "power bill", category: "Bills", type: "expense" },
  { keyword: "bescom", category: "Bills", type: "expense" },
  { keyword: "hescom", category: "Bills", type: "expense" },
  { keyword: "gescom", category: "Bills", type: "expense" },
  { keyword: "cesc", category: "Bills", type: "expense" },
  { keyword: "mseb", category: "Bills", type: "expense" },
  { keyword: "mahadiscom", category: "Bills", type: "expense" },
  { keyword: "bses", category: "Bills", type: "expense" },
  { keyword: "bses rajdhani", category: "Bills", type: "expense" },
  { keyword: "bses yamuna", category: "Bills", type: "expense" },
  { keyword: "tneb", category: "Bills", type: "expense" },
  { keyword: "tangedco", category: "Bills", type: "expense" },
  { keyword: "uppcl", category: "Bills", type: "expense" },
  { keyword: "wbsedcl", category: "Bills", type: "expense" },
  { keyword: "torrent power", category: "Bills", type: "expense" },
  { keyword: "tata power", category: "Bills", type: "expense" },
  { keyword: "adani electricity", category: "Bills", type: "expense" },
  { keyword: "dhbvn", category: "Bills", type: "expense" },
  { keyword: "uhbvn", category: "Bills", type: "expense" },
  { keyword: "pspcl", category: "Bills", type: "expense" },
  { keyword: "kseb", category: "Bills", type: "expense" },
  { keyword: "tsspdcl", category: "Bills", type: "expense" },
  { keyword: "apspdcl", category: "Bills", type: "expense" },
  { keyword: "gas cylinder", category: "Bills", type: "expense" },
  { keyword: "cylinder", category: "Bills", type: "expense" },
  { keyword: "indane", category: "Bills", type: "expense" },
  { keyword: "hp gas", category: "Bills", type: "expense" },
  { keyword: "bharat gas", category: "Bills", type: "expense" },
  { keyword: "lpg", category: "Bills", type: "expense" },
  { keyword: "piped gas", category: "Bills", type: "expense" },
  { keyword: "png", category: "Bills", type: "expense" },
  { keyword: "igl", category: "Bills", type: "expense" },
  { keyword: "mgl", category: "Bills", type: "expense" },
  { keyword: "mahanagar gas", category: "Bills", type: "expense" },
  { keyword: "adani total gas", category: "Bills", type: "expense" },
  { keyword: "gujarat gas", category: "Bills", type: "expense" },
  { keyword: "water bill", category: "Bills", type: "expense" },
  { keyword: "jal board", category: "Bills", type: "expense" },
  { keyword: "bwssb", category: "Bills", type: "expense" },
  { keyword: "rent", category: "Bills", type: "expense" },
  { keyword: "house rent", category: "Bills", type: "expense" },
  { keyword: "flat rent", category: "Bills", type: "expense" },
  { keyword: "room rent", category: "Bills", type: "expense" },
  { keyword: "pg rent", category: "Bills", type: "expense" },
  { keyword: "hostel rent", category: "Bills", type: "expense" },
  { keyword: "society maintenance", category: "Bills", type: "expense" },
  { keyword: "maintenance", category: "Bills", type: "expense" },
  { keyword: "mygate", category: "Bills", type: "expense" },
  { keyword: "nobroker", category: "Bills", type: "expense" },
  { keyword: "nobrokerhood", category: "Bills", type: "expense" },
  { keyword: "cred rent", category: "Bills", type: "expense" },
  { keyword: "property tax", category: "Bills", type: "expense" },
  { keyword: "municipal tax", category: "Bills", type: "expense" },
  { keyword: "maid salary", category: "Bills", type: "expense" },
  { keyword: "maid", category: "Bills", type: "expense" },
  { keyword: "kamwali", category: "Bills", type: "expense" },
  { keyword: "cook salary", category: "Bills", type: "expense" },
  { keyword: "cook", category: "Bills", type: "expense" },
  { keyword: "driver salary", category: "Bills", type: "expense" },
  { keyword: "driver", category: "Bills", type: "expense" },
  { keyword: "nanny", category: "Bills", type: "expense" },
  { keyword: "dhobi", category: "Bills", type: "expense" },
  { keyword: "newspaper bill", category: "Bills", type: "expense" },
  { keyword: "garbage fee", category: "Bills", type: "expense" },
  { keyword: "urban company", category: "Bills", type: "expense" },
  { keyword: "tata play", category: "Bills", type: "expense" },
  { keyword: "airtel dth", category: "Bills", type: "expense" },
  { keyword: "dish tv", category: "Bills", type: "expense" },
  { keyword: "sun direct", category: "Bills", type: "expense" },
  { keyword: "d2h", category: "Bills", type: "expense" },

  // 5. Health, Medical, Pharmacy, Diagnostics & Gym
  { keyword: "apollo pharmacy", category: "Health", type: "expense" },
  { keyword: "apollo 247", category: "Health", type: "expense" },
  { keyword: "medplus", category: "Health", type: "expense" },
  { keyword: "1mg", category: "Health", type: "expense" },
  { keyword: "tata 1mg", category: "Health", type: "expense" },
  { keyword: "netmeds", category: "Health", type: "expense" },
  { keyword: "pharmeasy", category: "Health", type: "expense" },
  { keyword: "wellness forever", category: "Health", type: "expense" },
  { keyword: "generic aadhaar", category: "Health", type: "expense" },
  { keyword: "jan aushadhi", category: "Health", type: "expense" },
  { keyword: "pharmacy", category: "Health", type: "expense" },
  { keyword: "chemist", category: "Health", type: "expense" },
  { keyword: "dawa", category: "Health", type: "expense" },
  { keyword: "medicine", category: "Health", type: "expense" },
  { keyword: "tablets", category: "Health", type: "expense" },
  { keyword: "dr lal pathlabs", category: "Health", type: "expense" },
  { keyword: "metropolis", category: "Health", type: "expense" },
  { keyword: "thyrocare", category: "Health", type: "expense" },
  { keyword: "srl diagnostics", category: "Health", type: "expense" },
  { keyword: "redcliffe", category: "Health", type: "expense" },
  { keyword: "blood test", category: "Health", type: "expense" },
  { keyword: "xray", category: "Health", type: "expense" },
  { keyword: "mri", category: "Health", type: "expense" },
  { keyword: "doctor fee", category: "Health", type: "expense" },
  { keyword: "consultation", category: "Health", type: "expense" },
  { keyword: "clinic", category: "Health", type: "expense" },
  { keyword: "hospital", category: "Health", type: "expense" },
  { keyword: "opd fee", category: "Health", type: "expense" },
  { keyword: "max hospital", category: "Health", type: "expense" },
  { keyword: "fortis", category: "Health", type: "expense" },
  { keyword: "manipal hospital", category: "Health", type: "expense" },
  { keyword: "narayana health", category: "Health", type: "expense" },
  { keyword: "aiims", category: "Health", type: "expense" },
  { keyword: "medanta", category: "Health", type: "expense" },
  { keyword: "cloudnine", category: "Health", type: "expense" },
  { keyword: "practo", category: "Health", type: "expense" },
  { keyword: "dentist", category: "Health", type: "expense" },
  { keyword: "eye checkup", category: "Health", type: "expense" },
  { keyword: "dr agarwals", category: "Health", type: "expense" },
  { keyword: "dermatologist", category: "Health", type: "expense" },
  { keyword: "cult.fit", category: "Health", type: "expense" },
  { keyword: "cure.fit", category: "Health", type: "expense" },
  { keyword: "gym", category: "Health", type: "expense" },
  { keyword: "gold's gym", category: "Health", type: "expense" },
  { keyword: "anytime fitness", category: "Health", type: "expense" },
  { keyword: "yoga", category: "Health", type: "expense" },
  { keyword: "protein powder", category: "Health", type: "expense" },
  { keyword: "muscleblaze", category: "Health", type: "expense" },
  { keyword: "patanjali", category: "Health", type: "expense" },
  { keyword: "himalaya", category: "Health", type: "expense" },
  { keyword: "dabur", category: "Health", type: "expense" },
  { keyword: "ayurveda", category: "Health", type: "expense" },
  { keyword: "health insurance", category: "Health", type: "expense" },
  { keyword: "star health", category: "Health", type: "expense" },
  { keyword: "hdfc ergo", category: "Health", type: "expense" },
  { keyword: "care health", category: "Health", type: "expense" },

  // 6. Entertainment, OTT, Cinema & Nightlife
  { keyword: "hotstar", category: "Entertainment", type: "expense" },
  { keyword: "disney+ hotstar", category: "Entertainment", type: "expense" },
  { keyword: "jiocinema", category: "Entertainment", type: "expense" },
  { keyword: "sonyliv", category: "Entertainment", type: "expense" },
  { keyword: "zee5", category: "Entertainment", type: "expense" },
  { keyword: "netflix", category: "Entertainment", type: "expense" },
  { keyword: "prime video", category: "Entertainment", type: "expense" },
  { keyword: "spotify", category: "Entertainment", type: "expense" },
  { keyword: "gaana", category: "Entertainment", type: "expense" },
  { keyword: "jiosaavn", category: "Entertainment", type: "expense" },
  { keyword: "wynk", category: "Entertainment", type: "expense" },
  { keyword: "youtube premium", category: "Entertainment", type: "expense" },
  { keyword: "aha", category: "Entertainment", type: "expense" },
  { keyword: "sun nxt", category: "Entertainment", type: "expense" },
  { keyword: "hoichoi", category: "Entertainment", type: "expense" },
  { keyword: "bookmyshow", category: "Entertainment", type: "expense" },
  { keyword: "bms", category: "Entertainment", type: "expense" },
  { keyword: "pvr", category: "Entertainment", type: "expense" },
  { keyword: "inox", category: "Entertainment", type: "expense" },
  { keyword: "cinepolis", category: "Entertainment", type: "expense" },
  { keyword: "movie ticket", category: "Entertainment", type: "expense" },
  { keyword: "insider.in", category: "Entertainment", type: "expense" },
  { keyword: "paytm insider", category: "Entertainment", type: "expense" },
  { keyword: "gaming cafe", category: "Entertainment", type: "expense" },
  { keyword: "steam", category: "Entertainment", type: "expense" },
  { keyword: "playstation", category: "Entertainment", type: "expense" },
  { keyword: "wonderla", category: "Entertainment", type: "expense" },
  { keyword: "imagica", category: "Entertainment", type: "expense" },
  { keyword: "pub", category: "Entertainment", type: "expense" },
  { keyword: "bar", category: "Entertainment", type: "expense" },
  { keyword: "brewery", category: "Entertainment", type: "expense" },
  { keyword: "clubbing", category: "Entertainment", type: "expense" },
  { keyword: "drinks", category: "Entertainment", type: "expense" },
  { keyword: "beer", category: "Entertainment", type: "expense" },
  { keyword: "theka", category: "Entertainment", type: "expense" },
  { keyword: "standup comedy", category: "Entertainment", type: "expense" },
  { keyword: "ipl ticket", category: "Entertainment", type: "expense" },

  // 7. Education, Coaching, Exams & EdTech
  { keyword: "physicswallah", category: "Education", type: "expense" },
  { keyword: "pw", category: "Education", type: "expense" },
  { keyword: "unacademy", category: "Education", type: "expense" },
  { keyword: "byjus", category: "Education", type: "expense" },
  { keyword: "vedantu", category: "Education", type: "expense" },
  { keyword: "allen", category: "Education", type: "expense" },
  { keyword: "aakash", category: "Education", type: "expense" },
  { keyword: "fiitjee", category: "Education", type: "expense" },
  { keyword: "resonance", category: "Education", type: "expense" },
  { keyword: "drishti ias", category: "Education", type: "expense" },
  { keyword: "vision ias", category: "Education", type: "expense" },
  { keyword: "made easy", category: "Education", type: "expense" },
  { keyword: "career launcher", category: "Education", type: "expense" },
  { keyword: "time institute", category: "Education", type: "expense" },
  { keyword: "udemy", category: "Education", type: "expense" },
  { keyword: "coursera", category: "Education", type: "expense" },
  { keyword: "upgrad", category: "Education", type: "expense" },
  { keyword: "scaler", category: "Education", type: "expense" },
  { keyword: "school fee", category: "Education", type: "expense" },
  { keyword: "college fee", category: "Education", type: "expense" },
  { keyword: "university fee", category: "Education", type: "expense" },
  { keyword: "tuition fee", category: "Education", type: "expense" },
  { keyword: "home tuition", category: "Education", type: "expense" },
  { keyword: "coaching fee", category: "Education", type: "expense" },
  { keyword: "exam fee", category: "Education", type: "expense" },
  { keyword: "upsc fee", category: "Education", type: "expense" },
  { keyword: "gate exam", category: "Education", type: "expense" },
  { keyword: "neet fee", category: "Education", type: "expense" },
  { keyword: "jee fee", category: "Education", type: "expense" },
  { keyword: "cat exam", category: "Education", type: "expense" },
  { keyword: "ielts fee", category: "Education", type: "expense" },
  { keyword: "books", category: "Education", type: "expense" },
  { keyword: "textbook", category: "Education", type: "expense" },
  { keyword: "stationary", category: "Education", type: "expense" },
  { keyword: "xerox", category: "Education", type: "expense" },
  { keyword: "printout", category: "Education", type: "expense" },

  // 8. Salary, Wages, Inflows & Bank Transfers
  { keyword: "salary", category: "Salary", type: "income" },
  { keyword: "salary credited", category: "Salary", type: "income" },
  { keyword: "monthly salary", category: "Salary", type: "income" },
  { keyword: "tcs salary", category: "Salary", type: "income" },
  { keyword: "infosys salary", category: "Salary", type: "income" },
  { keyword: "wipro salary", category: "Salary", type: "income" },
  { keyword: "accenture salary", category: "Salary", type: "income" },
  { keyword: "cognizant salary", category: "Salary", type: "income" },
  { keyword: "hcl salary", category: "Salary", type: "income" },
  { keyword: "capgemini salary", category: "Salary", type: "income" },
  { keyword: "deloitte salary", category: "Salary", type: "income" },
  { keyword: "google salary", category: "Salary", type: "income" },
  { keyword: "amazon salary", category: "Salary", type: "income" },
  { keyword: "paycheck", category: "Salary", type: "income" },
  { keyword: "payroll", category: "Salary", type: "income" },
  { keyword: "wage", category: "Salary", type: "income" },
  { keyword: "stipend", category: "Salary", type: "income" },
  { keyword: "internship stipend", category: "Salary", type: "income" },
  { keyword: "diwali bonus", category: "Salary", type: "income" },
  { keyword: "bonus credited", category: "Salary", type: "income" },
  { keyword: "incentive", category: "Salary", type: "income" },
  { keyword: "gratuity", category: "Salary", type: "income" },
  { keyword: "pf withdrawal", category: "Salary", type: "income" },
  { keyword: "pension", category: "Salary", type: "income" },
  { keyword: "upi received", category: "Salary", type: "income" },
  { keyword: "neft received", category: "Salary", type: "income" },
  { keyword: "imps received", category: "Salary", type: "income" },
  { keyword: "rtgs credited", category: "Salary", type: "income" },
  { keyword: "cash deposit", category: "Salary", type: "income" },
  { keyword: "cashback", category: "Other", type: "income" },
  { keyword: "gpay cashback", category: "Other", type: "income" },
  { keyword: "phonepe cashback", category: "Other", type: "income" },
  { keyword: "paytm cashback", category: "Other", type: "income" },
  { keyword: "cred cashback", category: "Other", type: "income" },

  // 9. Freelance, Business & Settlements
  { keyword: "freelance", category: "Freelance", type: "income" },
  { keyword: "client payment", category: "Freelance", type: "income" },
  { keyword: "upwork payout", category: "Freelance", type: "income" },
  { keyword: "fiverr payout", category: "Freelance", type: "income" },
  { keyword: "razorpay payout", category: "Freelance", type: "income" },
  { keyword: "cashfree payout", category: "Freelance", type: "income" },
  { keyword: "instamojo", category: "Freelance", type: "income" },
  { keyword: "paytm merchant", category: "Freelance", type: "income" },
  { keyword: "bharatpe settlement", category: "Freelance", type: "income" },
  { keyword: "consulting fee", category: "Freelance", type: "income" },
  { keyword: "vendor payment", category: "Freelance", type: "income" },
  { keyword: "shop income", category: "Freelance", type: "income" },
  { keyword: "invoice paid", category: "Freelance", type: "income" },

  // 10. Investment, Mutual Funds, SIP, Gold & Deposits
  { keyword: "zerodha", category: "Investment", type: "expense" },
  { keyword: "kite", category: "Investment", type: "expense" },
  { keyword: "groww", category: "Investment", type: "expense" },
  { keyword: "angel one", category: "Investment", type: "expense" },
  { keyword: "upstox", category: "Investment", type: "expense" },
  { keyword: "indmoney", category: "Investment", type: "expense" },
  { keyword: "kuvera", category: "Investment", type: "expense" },
  { keyword: "etmoney", category: "Investment", type: "expense" },
  { keyword: "coin zerodha", category: "Investment", type: "expense" },
  { keyword: "dhan", category: "Investment", type: "expense" },
  { keyword: "5paisa", category: "Investment", type: "expense" },
  { keyword: "paytm money", category: "Investment", type: "expense" },
  { keyword: "motilal oswal", category: "Investment", type: "expense" },
  { keyword: "icici direct", category: "Investment", type: "expense" },
  { keyword: "hdfc securities", category: "Investment", type: "expense" },
  { keyword: "kotak securities", category: "Investment", type: "expense" },
  { keyword: "sbi securities", category: "Investment", type: "expense" },
  { keyword: "sip", category: "Investment", type: "expense" },
  { keyword: "mutual fund", category: "Investment", type: "expense" },
  { keyword: "mf sip", category: "Investment", type: "expense" },
  { keyword: "index fund", category: "Investment", type: "expense" },
  { keyword: "nifty 50", category: "Investment", type: "expense" },
  { keyword: "elss", category: "Investment", type: "expense" },
  { keyword: "tata mutual fund", category: "Investment", type: "expense" },
  { keyword: "hdfc mutual fund", category: "Investment", type: "expense" },
  { keyword: "sbi mutual fund", category: "Investment", type: "expense" },
  { keyword: "icici prudential", category: "Investment", type: "expense" },
  { keyword: "axis mutual fund", category: "Investment", type: "expense" },
  { keyword: "parag parikh", category: "Investment", type: "expense" },
  { keyword: "ppfas", category: "Investment", type: "expense" },
  { keyword: "quant mutual fund", category: "Investment", type: "expense" },
  { keyword: "nps", category: "Investment", type: "expense" },
  { keyword: "ppf", category: "Investment", type: "expense" },
  { keyword: "sukanya samriddhi", category: "Investment", type: "expense" },
  { keyword: "fd", category: "Investment", type: "expense" },
  { keyword: "fixed deposit", category: "Investment", type: "expense" },
  { keyword: "rd", category: "Investment", type: "expense" },
  { keyword: "recurring deposit", category: "Investment", type: "expense" },
  { keyword: "post office scheme", category: "Investment", type: "expense" },
  { keyword: "sgb", category: "Investment", type: "expense" },
  { keyword: "sovereign gold bond", category: "Investment", type: "expense" },
  { keyword: "digital gold", category: "Investment", type: "expense" },
  { keyword: "gold chit", category: "Investment", type: "expense" },
  { keyword: "tanishq golden harvest", category: "Investment", type: "expense" },
  { keyword: "kalyan gold scheme", category: "Investment", type: "expense" },
  { keyword: "treasury bills", category: "Investment", type: "expense" },
  { keyword: "bonds", category: "Investment", type: "expense" },
  { keyword: "wint wealth", category: "Investment", type: "expense" },
  { keyword: "grip invest", category: "Investment", type: "expense" },
  { keyword: "stocks", category: "Investment", type: "expense" },
  { keyword: "shares", category: "Investment", type: "expense" },
  { keyword: "ipo application", category: "Investment", type: "expense" },
  { keyword: "crypto", category: "Investment", type: "expense" },
  { keyword: "bitcoin", category: "Investment", type: "expense" },
  { keyword: "wazirx", category: "Investment", type: "expense" },
  { keyword: "coindcx", category: "Investment", type: "expense" },
  { keyword: "dividend", category: "Investment", type: "income" },
  { keyword: "dividend credited", category: "Investment", type: "income" },
  { keyword: "interest credited", category: "Investment", type: "income" },

  // 11. Gifts, Shagun, Festivals, Temple & Daan
  { keyword: "shagun", category: "Gift", type: "expense" },
  { keyword: "shagun lifafa", category: "Gift", type: "expense" },
  { keyword: "lifafa", category: "Gift", type: "expense" },
  { keyword: "rakhi gift", category: "Gift", type: "expense" },
  { keyword: "diwali gift", category: "Gift", type: "expense" },
  { keyword: "wedding gift", category: "Gift", type: "expense" },
  { keyword: "marriage gift", category: "Gift", type: "expense" },
  { keyword: "birthday gift", category: "Gift", type: "expense" },
  { keyword: "anniversary gift", category: "Gift", type: "expense" },
  { keyword: "eidi", category: "Gift", type: "expense" },
  { keyword: "bhai dooj", category: "Gift", type: "expense" },
  { keyword: "housewarming gift", category: "Gift", type: "expense" },
  { keyword: "griha pravesh", category: "Gift", type: "expense" },
  { keyword: "temple donation", category: "Gift", type: "expense" },
  { keyword: "mandir daan", category: "Gift", type: "expense" },
  { keyword: "gurudwara daan", category: "Gift", type: "expense" },
  { keyword: "hundi", category: "Gift", type: "expense" },
  { keyword: "tirupati", category: "Gift", type: "expense" },
  { keyword: "shirdi donation", category: "Gift", type: "expense" },
  { keyword: "daan", category: "Gift", type: "expense" },
  { keyword: "annadanam", category: "Gift", type: "expense" },
  { keyword: "gau seva", category: "Gift", type: "expense" },
  { keyword: "charity", category: "Gift", type: "expense" },
  { keyword: "donation", category: "Gift", type: "expense" },
  { keyword: "pm cares", category: "Gift", type: "expense" },
  { keyword: "akshaya patra", category: "Gift", type: "expense" },
  { keyword: "give india", category: "Gift", type: "expense" },
  { keyword: "ketto", category: "Gift", type: "expense" },
  { keyword: "milaap", category: "Gift", type: "expense" },
];

// Initialize Fuse instance with complete Indian dataset
const fuse = new Fuse(INDIAN_TRAINING_DATA, {
  keys: ["keyword"],
  threshold: 0.35,
  distance: 100,
  minMatchCharLength: 2,
  includeScore: true,
});

/**
 * Predicts category and transaction type from user text input
 * @param {string} text - The input text typed by the user
 * @returns {{ category: string, type: string, confidence: number, isAutoDetected: boolean, categoryMeta: Object }}
 */
export function autoCategorize(text) {
  if (!text || typeof text !== "string" || text.trim().length === 0) {
    return {
      category: "Other",
      type: "expense",
      confidence: 0,
      isAutoDetected: false,
      categoryMeta: CATEGORIES.find((c) => c.id === "Other"),
    };
  }

  const cleanedText = text.trim().toLowerCase();

  // 1. Direct Substring / Exact Keyword Check (0ms fastest match)
  for (const item of INDIAN_TRAINING_DATA) {
    if (cleanedText.includes(item.keyword)) {
      const meta = CATEGORIES.find((c) => c.id === item.category) || CATEGORIES[CATEGORIES.length - 1];
      let finalType = item.type;
      if (cleanedText.includes("maid") || cleanedText.includes("cook") || cleanedText.includes("driver salary") || cleanedText.includes("salary paid")) {
        finalType = "expense";
      }
      return {
        category: item.category,
        type: finalType,
        confidence: 1.0,
        isAutoDetected: true,
        matchedKeyword: item.keyword,
        categoryMeta: meta,
      };
    }
  }

  // 2. Tokenized Fuzzy Matching with Fuse.js (Handles typos e.g. swigy, zomto, blnkt, rapdo, flpkrt)
  const tokens = cleanedText.split(/\s+/).filter((t) => t.length >= 2);
  let bestResult = null;
  let lowestScore = 1.0;

  // Check full text first
  const fullResults = fuse.search(cleanedText);
  if (fullResults.length > 0 && fullResults[0].score < 0.4) {
    bestResult = fullResults[0].item;
    lowestScore = fullResults[0].score;
  } else {
    // Check individual word tokens
    for (const token of tokens) {
      const results = fuse.search(token);
      if (results.length > 0 && results[0].score < lowestScore) {
        lowestScore = results[0].score;
        bestResult = results[0].item;
      }
    }
  }

  if (bestResult && lowestScore <= 0.4) {
    const meta = CATEGORIES.find((c) => c.id === bestResult.category) || CATEGORIES[CATEGORIES.length - 1];
    return {
      category: bestResult.category,
      type: bestResult.type,
      confidence: Math.round((1 - lowestScore) * 100) / 100,
      isAutoDetected: true,
      matchedKeyword: bestResult.keyword,
      categoryMeta: meta,
    };
  }

  // Default fallback
  const defaultMeta = CATEGORIES.find((c) => c.id === "Other");
  return {
    category: "Other",
    type: "expense",
    confidence: 0,
    isAutoDetected: false,
    categoryMeta: defaultMeta,
  };
}

/**
 * Helper to get Category Metadata by ID
 */
export function getCategoryMeta(categoryId) {
  return CATEGORIES.find((c) => c.id === categoryId) || CATEGORIES.find((c) => c.id === "Other");
}
